// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/harshitasao/Microservices-Go/product-api/client/models"
)

// DeleteProductsReader is a Reader for the DeleteProducts structure.
type DeleteProductsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteProductsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDeleteProductsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteProductsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewDeleteProductsNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteProductsCreated creates a DeleteProductsCreated with default headers values
func NewDeleteProductsCreated() *DeleteProductsCreated {
	return &DeleteProductsCreated{}
}

/*
DeleteProductsCreated describes a response with status code 201, with default header values.

No content is returned by this API endpoint
*/
type DeleteProductsCreated struct {
}

// IsSuccess returns true when this delete products created response has a 2xx status code
func (o *DeleteProductsCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete products created response has a 3xx status code
func (o *DeleteProductsCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete products created response has a 4xx status code
func (o *DeleteProductsCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete products created response has a 5xx status code
func (o *DeleteProductsCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this delete products created response a status code equal to that given
func (o *DeleteProductsCreated) IsCode(code int) bool {
	return code == 201
}

func (o *DeleteProductsCreated) Error() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteProductsCreated ", 201)
}

func (o *DeleteProductsCreated) String() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteProductsCreated ", 201)
}

func (o *DeleteProductsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteProductsNotFound creates a DeleteProductsNotFound with default headers values
func NewDeleteProductsNotFound() *DeleteProductsNotFound {
	return &DeleteProductsNotFound{}
}

/*
DeleteProductsNotFound describes a response with status code 404, with default header values.

Generic error message returned as a string
*/
type DeleteProductsNotFound struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this delete products not found response has a 2xx status code
func (o *DeleteProductsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete products not found response has a 3xx status code
func (o *DeleteProductsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete products not found response has a 4xx status code
func (o *DeleteProductsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete products not found response has a 5xx status code
func (o *DeleteProductsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete products not found response a status code equal to that given
func (o *DeleteProductsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeleteProductsNotFound) Error() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteProductsNotFound  %+v", 404, o.Payload)
}

func (o *DeleteProductsNotFound) String() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteProductsNotFound  %+v", 404, o.Payload)
}

func (o *DeleteProductsNotFound) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DeleteProductsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteProductsNotImplemented creates a DeleteProductsNotImplemented with default headers values
func NewDeleteProductsNotImplemented() *DeleteProductsNotImplemented {
	return &DeleteProductsNotImplemented{}
}

/*
DeleteProductsNotImplemented describes a response with status code 501, with default header values.

Generic error message returned as a string
*/
type DeleteProductsNotImplemented struct {
	Payload *models.GenericError
}

// IsSuccess returns true when this delete products not implemented response has a 2xx status code
func (o *DeleteProductsNotImplemented) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete products not implemented response has a 3xx status code
func (o *DeleteProductsNotImplemented) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete products not implemented response has a 4xx status code
func (o *DeleteProductsNotImplemented) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete products not implemented response has a 5xx status code
func (o *DeleteProductsNotImplemented) IsServerError() bool {
	return true
}

// IsCode returns true when this delete products not implemented response a status code equal to that given
func (o *DeleteProductsNotImplemented) IsCode(code int) bool {
	return code == 501
}

func (o *DeleteProductsNotImplemented) Error() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteProductsNotImplemented  %+v", 501, o.Payload)
}

func (o *DeleteProductsNotImplemented) String() string {
	return fmt.Sprintf("[DELETE /products/{id}][%d] deleteProductsNotImplemented  %+v", 501, o.Payload)
}

func (o *DeleteProductsNotImplemented) GetPayload() *models.GenericError {
	return o.Payload
}

func (o *DeleteProductsNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GenericError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
